(function (root) {
  "use strict";
  // 资料来源：gan-phd-radar（dist/data.js，只读取未改动）＋《欧洲博士制度比较与申请策略》2026-10。
  // 分组沿用该指南：按申请机制分 A／B／C，不按地理。
  const VERIFIED_AT = "2026-10-06T07:56:56+08:00";

  const GROUPS = [
    { id: "A", name: "Vacancy / Job Style", countries: ["荷兰", "瑞典", "丹麦", "挪威"],
      idea: "不是申「学校」，而是投「职缺」。职缺本身通常就是 funded position。",
      materials: ["1–2 页 academic CV", "针对该职缺的 motivation letter", "成绩单／学位证明", "推荐人／publication list", "「我如何直接解决这个 project」的证据"],
      steps: ["找 vacancy：用题目／技能搜，别先绑死学校", "读 Job Description：抓 project goal、methods、must-have skills、deadline、contract", "做 Match Matrix：每条要求对应你做过的实验／TCAD／量测／论文", "客制 Motivation Letter：主轴是「为何我能做这个 project」", "正式系统投递：套磁可辅助，不能取代 portal submission", "Interview：备 5–10 分钟研究简报 + 对 project 的技术理解"] },
    { id: "B", name: "Supervisor + Project Hybrid", countries: ["德国", "法国", "比利时"],
      idea: "教授与 funding 都重要，但正式职缺仍须正式投递。套磁的目的是确认位置与经费，不是「求收」。",
      materials: ["academic CV", "150–250 字套磁信", "1 页 research-fit brief", "针对教授近期 paper 的匹配点", "同时盯公开 vacancy"],
      steps: ["套磁信回答四件事：我是谁／为什么找你／我能带来什么／我在问什么（2027 是否有 fully funded position、走哪个 portal）", "收到正面回复后确认：已有 project funding 吗？", "是 employee contract、doctoral scholarship，还是只先拿 admission？", "合约年限与 full-time／percentage？", "是否还要正式投 university HR portal？doctoral school 是否另外申请？", "IELTS／English proof 是 admission requirement 还是招聘 requirement？"] },
    { id: "C", name: "Admission + Funding Dual Track", countries: ["芬兰"],
      idea: "最容易误判：拿到 study right 之后，仍要问「薪资／奖学金是否已确定？」supervisor 愿意指导 ≠ paid position 已确定。",
      materials: ["doctoral programme application", "supervisor support / research plan", "另外一套 funding / paid position 申请", "Funding Checklist"],
      steps: ["先申 doctoral programme 取得 study right", "另外确认 paid doctoral researcher position 或 grant", "两者都到位才算 fully funded"] },
  ];

  const SYSTEMS = [
    { country: "德国", code: "DE", group: "B",
      identity: "博士候选人；受聘时也是研究员工", entry: "Individual PhD／structured programme／公开职缺",
      funding: "录取与资金不一定绑定；先辨认 TV-L、职位比例、奖学金或外部资金", coursework: "Individual 路径通常较少；结构化项目另有课程",
      action: "公开缺直接投；没有缺但高度匹配时，用套磁确认专案与资金。", sources: "DAAD PhDGermany、Research in Germany、EURAXESS、学校 jobs、PI 网页" },
    { country: "法国", code: "FR", group: "B",
      identity: "常见 funded doctoral researcher／doctoral contract", entry: "Sujet de thèse／实验室／doctoral school",
      funding: "多数理工 funded PhD 会明确绑定 doctoral contract、project 或 CIFRE", coursework: "doctoral school training＋研究",
      action: "同时追题目与 PI；教授正面回复后，仍要确认合约与博士学院程序。", sources: "EURAXESS、博士学院／实验室、ABG、学校 jobs" },
    { country: "比利时", code: "BE", group: "B",
      identity: "PhD scholarship holder 或 research associate", entry: "公开 PhD vacancy＋PI／project",
      funding: "通常跟 project 或 scholarship 绑定；依校规与协议", coursework: "doctoral training；研究比重通常较高",
      action: "公开职缺优先正式投；另用 PI 管线追 KU Leuven、imec、Ghent 的下一轮。", sources: "KU Leuven／Ghent／imec jobs、EURAXESS" },
    { country: "荷兰", code: "NL", group: "A",
      identity: "多数 funded PhD 为大学员工", entry: "直接投 PhD vacancy",
      funding: "职缺本身通常就是 funded position；薪资依 collective labour agreement", coursework: "研究为主；Graduate School training 通常在入职后完成",
      action: "把博士当研究职缺投：先读 JD，再针对 project 客制材料。", sources: "AcademicTransfer、各大学 jobs、EURAXESS" },
    { country: "瑞典", code: "SE", group: "A",
      identity: "常见 doctoral student employment", entry: "公开 doctoral position",
      funding: "多数 vacancy 同时是博士职位与受聘关系", coursework: "coursework＋thesis；比例依学科与项目",
      action: "直接走 HR／大学系统；教授联络只用于具体技术澄清。", sources: "各大学 vacancies、EURAXESS、Academic Positions" },
    { country: "丹麦", code: "DK", group: "A",
      identity: "常见固定期限受聘 PhD", entry: "公开 PhD position＋enrolment",
      funding: "通常绑定；标准路径常为 3 年全职聘雇", coursework: "以 UCPH 为例约 28–35 ECTS；研究、教学与训练并行",
      action: "先按 vacancy 要求投递，录取后再完成 enrolment。", sources: "各大学 jobs、EURAXESS" },
    { country: "挪威", code: "NO", group: "A",
      identity: "常见 PhD research fellow／employee-like position", entry: "公开 PhD／research fellow vacancy",
      funding: "多数公开职缺已附 salary／funding", coursework: "以 NTNU 自然科学为例约 30 credits",
      action: "用 Jobbnorge 与大学 vacancies 找职缺，再回原页核对薪资和任职条件。", sources: "Jobbnorge、各大学 vacancies、EURAXESS" },
    { country: "芬兰", code: "FI", group: "C",
      identity: "doctoral researcher 与 doctoral student 可能不是同一身分", entry: "doctoral programme＋paid position，两者可能分开申请",
      funding: "study right 不代表有 salary；必须另外确认 paid position 或完整资金", coursework: "program-specific doctoral training",
      action: "先拆开 admission 与 funding，拿到 study right 后仍要确认谁付薪、付多久。", sources: "Studyinfo、各校 jobs、EURAXESS、Work in Finland Academic" },
  ];

  const JOBS = [
    { id: "de-fraunhofer-iaf-84765", country: "德国", city: "Freiburg", status: "active", relevance: "core",
      title: "Promotion im Bereich GaN-Schaltungen für höchste Leistung", organization: "Fraunhofer IAF · 微电子部门",
      deadlineText: "未公布；官方页仍可申请", startDate: "未公开", salary: "依德国公共服务 TVöD；公告未列薪级／比例",
      skills: ["电机、微系统、通讯工程或物理硕士", "ADS、CST、HFSS 等电路／电磁模拟", "半导体元件量测表征", "S-parameter 与 Load-pull 量测"],
      note: "题目偏高功率 RF/MMIC，但核心技术直接使用 GaN HEMT 元件、量测与热管理。", sourceName: "Fraunhofer 官方招聘", sourceUrl: "https://jobs.fraunhofer.de/job/Freiburg-Promotion-im-Bereich-GaN-Schaltungen-f%C3%BCr-h%C3%B6chste-Leistung-79108/1406057433/" },
    { id: "fr-cea-mos-hemt-39605", country: "法国", city: "Grenoble / Lille", status: "active", relevance: "core",
      title: "GaN MOS-HEMT 的可靠度与动态特性：埋层障壁与基板影响", organization: "CEA-Leti × IEMN / CNRS",
      deadlineText: "Rolling；官方页仍列出，建议立即联络", startDate: "2026-10-01（官方原定）", salary: "官方公告未公开",
      skills: ["材料物理、微电子元件或相关硕士／工程师学位", "半导体元件物理", "电性量测与可靠度分析", "TCAD／制程工程经验属高度相关能力"],
      note: "CEA／INSTN 官方题目页仍在线；CEA 说明博士题目全年 rolling 收件。原定开始日已过，建议立即向 Romain Lavieville 确认实际到职安排。", sourceName: "CEA／INSTN 官方博士题目", sourceUrl: "https://www.theses-postdocs.cea.fr/offre-de-emploi/emploi-fiabilite-et-proprietes-dynamiques-des-mos-hemt-gan-impact-de-la-barriere-enterree-et-du-type-de-subst_39605.aspx" },
    { id: "fr-cea-vertical-gan-138244", country: "法国", city: "Grenoble", status: "active", relevance: "core",
      title: "垂直 GaN 功率电晶体闸极模组开发", organization: "CEA-Leti × Université Grenoble Alpes × LTM/CNRS",
      deadlineText: "Rolling；官方页仍列出，建议立即联络", startDate: "2026-10-01（官方原定）", salary: "未公开；标示为公私混合资助",
      skills: ["微电子元件物理的工程师或 Master 2", "GaN 功率元件", "材料工程、元件表征或元件模拟", "电性量测"],
      note: "CEA／INSTN 官方题目页仍在线；CEA 说明博士题目全年 rolling 收件。原定开始日已过，应立即向 Julien Buckley 确认实际到职安排。", sourceName: "CEA／INSTN 官方博士题目", sourceUrl: "https://instn.cea.fr/these/developpement-du-module-de-grille-pour-transistors-de-puissance-verticaux-en-gan/" },
    { id: "fr-cea-gan-pa-138291", country: "法国", city: "Gramat / Toulouse", status: "active", relevance: "adjacent",
      title: "高功率创新 GaN RF 放大器设计", organization: "CEA Gramat × Université Toulouse III × LAAS-CNRS",
      deadlineText: "Rolling；官方页仍列出，建议立即联络", startDate: "2026-10-01（官方原定）", salary: "未公开；标示为公私混合资助",
      skills: ["电子工程硕士或工程师学位", "GaN 元件物理与 RF 功率放大器", "电磁／电路设计", "原型开发能力"],
      note: "CEA 官方题目页仍在线且采 rolling 收件；偏 RF 高功率与国防应用，资格或安全审查条件未在公告中列出，应直接询问。", sourceName: "CEA 官方博士题目", sourceUrl: "https://www.theses-postdocs.cea.fr/offre-de-emploi/emploi-conception-d-un-amplificateur-rf-de-puissance-gan-innovant_38633.aspx" },
    { id: "fr-iemn-gan-pin-rf-2026", country: "法国", city: "Villeneuve-d'Ascq / Lille", status: "verify", relevance: "core",
      title: "GaN PIN 二极体：超快速高功率 RF 开关与限幅器", organization: "Université de Lille × CNRS · IEMN",
      deadlineText: "未公布；资助与收件状态需向指导教授确认", startDate: "未公开", salary: "官方题目页未公开；资助状态需确认",
      skills: ["半导体元件物理、微电子或相关硕士", "GaN 宽能隙元件", "元件制程、电性／RF 表征或 TCAD", "高功率 RF 开关与保护电路"],
      note: "官方 2026 博士题目页仍列出此题并提供申请入口，但未清楚公开截止日与最终资助状态，因此列为『需确认』。", sourceName: "IEMN 官方博士题目页", sourceUrl: "https://www.iemn.fr/en/formation/sujets-de-theses" },
    { id: "be-imec-fall-2026", country: "比利时", city: "Leuven（主要地点）", status: "upcoming", relevance: "core",
      title: "imec 2026 秋季博士主题征集（GaN 题目待公布）", organization: "imec × 比利时合作大学",
      deadlineText: "2026 秋季开放；确切日期待公告", startDate: "录取后协议", salary: "提供财务支持；金额待录取与合约阶段确认",
      skills: ["申请截止前已完成硕士", "依个别 GaN／半导体主题匹配技术背景", "履历、动机信、学位与成绩单", "1 封独立推荐信"],
      note: "这是即将开放的集中申请入口，GaN Power 具体题目需等秋季清单。", sourceName: "imec 官方博士申请页", sourceUrl: "https://www.imec-int.com/en/work-at-imec/job-opportunities/phd-at-imec" },
    { id: "nl-utwente-sensor-2594-a", country: "荷兰", city: "Enschede", status: "active", relevance: "adjacent",
      title: "PhD 1：GaN／SiC 快速切换用超宽频电流感测器", organization: "University of Twente × VSL · Moore4Power",
      deadlineText: "2026-10-16", startDate: "2026 秋季（可协调）", salary: "€3,204–€4,051／月（税前，随年资递增）",
      skills: ["电机或近似领域硕士", "类比、RF／微波、宽频感测或高频量测", "EM／电路模拟、PCB、VNA、示波器经验加分", "理论建模、实验与定量资料分析"],
      note: "属 GaN 功率元件的超高速量测与损耗评估，对 device characterization 很匹配。", sourceName: "AcademicTransfer／UT 官方职缺", sourceUrl: "https://www.academictransfer.com/en/jobs/363997/2-phd-positions-on-measuring-the-future-of-power-electronics" },
    { id: "nl-utwente-calorimetry-2594-b", country: "荷兰", city: "Enschede", status: "active", relevance: "adjacent",
      title: "PhD 2：GaN／SiC 转换器的可溯源效率与热量测", organization: "University of Twente × VSL · Moore4Power",
      deadlineText: "2026-10-16", startDate: "2026 秋季（可协调）", salary: "€3,204–€4,051／月（税前，随年资递增）",
      skills: ["电机、应用物理或近似领域硕士", "电性量测、电力电子、仪器或实验物理", "不确定度、资料撷取、转换器测试、热模型或量热经验加分", "整合多感测系统与实验设计"],
      note: "偏 converter-level efficiency 与 metrology，但直接测试 GaN 功率器件与转换器。", sourceName: "AcademicTransfer／UT 官方职缺", sourceUrl: "https://www.academictransfer.com/en/jobs/363997/2-phd-positions-on-measuring-the-future-of-power-electronics" },
    { id: "se-kth-gan-converters-2026", country: "瑞典", city: "Stockholm", status: "closed", relevance: "adjacent",
      title: "模组化 GaN 转换器电力电子博士（近期已截止）", organization: "KTH Royal Institute of Technology · EECS",
      deadlineText: "2026-05-31（已截止）", startDate: "2026-08-01 或协议提前", salary: "依 KTH 博士薪资协议按月给付；金额未列",
      skills: ["电力电子与转换器拓扑", "GaN 功率半导体", "可靠度、控制与高功率驱动应用"],
      note: "已截止，保留作为研究团队与下一轮相似职缺的线索。", sourceName: "KTH 官方招聘（已下架）", sourceUrl: "https://www.kth.se/lediga-jobb/922337?l=sv" },
    { id: "fr-cnrs-1200v-gan-2026", country: "法国", city: "Toulouse", status: "closed", relevance: "core",
      title: "耐压超过 1200 V 的 normally-off GaN HEMT（近期已截止）", organization: "CNRS / LAAS · Université de Toulouse",
      deadlineText: "2026-06-17（已截止）", startDate: "原公告未在摘要中列明", salary: "未公开",
      skills: ["GaN HEMT 元件物理", "normally-off 架构", "元件设计、制作与表征", "高压功率半导体"],
      note: "已截止，但与你的方向高度一致，值得追踪 LAAS/CNRS 后续题目。", sourceName: "法国公共服务职缺平台", sourceUrl: "https://choisirleservicepublic.gouv.fr/offre-emploi/offre-de-these--nouveau-dispositif-electronique-de-puissance-en-gan-supportant-des-tensions-superieure-reference-UPR8001-FREMOR-020/" },
  ];

  const SOURCES = [
    { country: "跨国", name: "EURAXESS Jobs", kind: "欧盟研究职缺总入口", cadence: "每日", url: "https://euraxess.ec.europa.eu/jobs/search", note: "先发现，再回原机构页核对。" },
    { country: "跨国", name: "Academic Positions", kind: "学术职缺聚合", cadence: "每日", url: "https://academicpositions.com/find-jobs", note: "适合关键字 GaN、wide-bandgap、power electronics。" },
    { country: "跨国", name: "FindAPhD", kind: "博士题目聚合", cadence: "每周", url: "https://www.findaphd.com/phds/?Keywords=GaN%20power", note: "英语题目较多，须回官方页确认。" },
    { country: "跨国", name: "MSCA Doctoral Networks", kind: "欧盟博士网络", cadence: "每周", url: "https://marie-sklodowska-curie-actions.ec.europa.eu/actions/doctoral-networks", note: "留意 mobility rule 与多国 secondment。" },
    { country: "德国", name: "Fraunhofer Jobs", kind: "研究机构官方", cadence: "每日", url: "https://jobs.fraunhofer.de/", note: "重点监测 IAF、ISIT、IISB。" },
    { country: "德国", name: "University of Stuttgart · Smart Converters", kind: "大学研究团队官方", cadence: "每周", url: "https://www.iew.uni-stuttgart.de/forschung/smarteConverter/", note: "GaN Power IC、双向／1200 V GaN 与 ERC 博士机会。" },
    { country: "德国", name: "TU Dresden · Power Electronics", kind: "大学研究团队官方", cadence: "每周", url: "https://tu-dresden.de/ing/elektrotechnik/eti/le", note: "GaN HEMT 表征、短路保护与 gate driver。" },
    { country: "德国", name: "TUM · Energy Conversion Technology", kind: "大学研究团队官方", cadence: "每周", url: "https://www.epe.ed.tum.de/en/ewt/", note: "慕尼黑的 GaN converter／automotive system 线索。" },
    { country: "德国", name: "Kiel University · Power Electronics", kind: "大学研究团队官方", cadence: "每周", url: "https://www.uni-kiel.de/en/tf/research/institute-etit/power-electronics", note: "GaNius、双向 GaN、converter topology 与热可靠度。" },
    { country: "德国", name: "Fraunhofer ISIT · GaN Devices", kind: "研究机构／大学联合", cadence: "每周", url: "https://www.isit.fraunhofer.de/en/technology/power-electronic/semiconductor-technology-for-powerdevices/gan.html", note: "垂直 GaN、8 吋制程、GaN-on-Si 与元件可靠度。" },
    { country: "德国", name: "Fraunhofer IISB · SiC/GaN Converters", kind: "研究机构官方", cadence: "每周", url: "https://www.iisb.fraunhofer.de/en/research_areas/leistungselektronik/sic_gan_converters.html", note: "静态／动态表征、模组与 converter validation。" },
    { country: "德国", name: "PhDGermany · DAAD", kind: "全德博士入口", cadence: "每周", url: "https://www.daad.de/en/studying-in-germany/phd-studies-research/phd-germany/", note: "包含职缺与结构化博士项目。" },
    { country: "德国", name: "Helmholtz Jobs", kind: "研究中心官方", cadence: "每周", url: "https://www.helmholtz.de/en/career/job-vacancies/", note: "可搜 semiconductor、power electronics。" },
    { country: "法国", name: "CEA／INSTN 博士题目", kind: "CEA 官方", cadence: "每日", url: "https://instn.cea.fr/these/", note: "GaN、SiC、可靠度与制程的重要来源；官方说明题目全年 rolling 收件。" },
    { country: "法国", name: "CNRS Emploi", kind: "CNRS 官方", cadence: "每日", url: "https://emploi.cnrs.fr/Offres.aspx", note: "搜寻 doctorant、GaN、HEMT、électronique de puissance。" },
    { country: "法国", name: "ABG", kind: "法国博士职缺平台", cadence: "每日", url: "https://www.abg.asso.fr/fr/recrutement/sujet-de-these", note: "CEA 与大学博士题目密集。" },
    { country: "法国", name: "ADUM", kind: "博士申请平台", cadence: "每周", url: "https://www.adum.fr/", note: "部分题目需透过博士学院页进入。" },
    { country: "法国", name: "IEMN 博士题目", kind: "大学／CNRS 实验室官方", cadence: "每周", url: "https://www.iemn.fr/en/formation/sujets-de-theses", note: "直接追踪 WIND 团队的 GaN 元件、制程与 RF 题目。" },
    { country: "比利时", name: "imec PhD", kind: "研究机构官方", cadence: "每日", url: "https://www.imec-int.com/en/work-at-imec/job-opportunities/phd-at-imec", note: "秋季集中征集，GaN Power 优先监测。" },
    { country: "比利时", name: "比利时鲁汶大学（KU Leuven）Jobs", kind: "大学官方", cadence: "每日", url: "https://www.kuleuven.be/personeel/jobsite/jobs/academic", note: "追踪 ELECTA、ESAT、EnergyVille 与 GaN Power 题目。" },
    { country: "比利时", name: "鲁汶大学 ELECTA Research Portal", kind: "大学研究团队官方", cadence: "每周", url: "https://research.kuleuven.be/portal/en/unit/50000518", note: "核对 GaN Power Electronics 计划、教授与在研博士题目。" },
    { country: "比利时", name: "Ghent University Vacancies", kind: "大学官方", cadence: "每周", url: "https://www.ugent.be/en/work/vacancies", note: "追踪器件建模、RF、功率电子。" },
    { country: "荷兰", name: "AcademicTransfer", kind: "荷兰学术职缺主入口", cadence: "每日", url: "https://www.academictransfer.com/en/jobs/?q=GaN", note: "荷兰大学与研究机构覆盖最佳。" },
    { country: "荷兰", name: "University of Twente Jobs", kind: "大学官方", cadence: "每日", url: "https://www.utwente.nl/en/organisation/careers/", note: "重点监测 power electronics 与 semiconductor devices。" },
    { country: "荷兰", name: "TU Delft Vacancies", kind: "大学官方", cadence: "每周", url: "https://www.tudelft.nl/en/about-tu-delft/working-at-tu-delft/search-jobs", note: "追踪 microelectronics、power conversion。" },
    { country: "北欧", name: "KTH Vacancies", kind: "瑞典大学官方", cadence: "每日", url: "https://www.kth.se/en/om/work-at-kth/lediga-jobb", note: "曾出现 Moore4Power GaN 转换器职缺。" },
    { country: "北欧", name: "Chalmers Vacancies", kind: "瑞典大学官方", cadence: "每周", url: "https://www.chalmers.se/en/about-chalmers/work-with-us/vacancies/", note: "追踪 electric power engineering。" },
    { country: "北欧", name: "DTU Vacancies", kind: "丹麦大学官方", cadence: "每周", url: "https://www.dtu.dk/english/about/job-and-career/vacant-positions", note: "搜寻 power electronics、wide bandgap。" },
    { country: "北欧", name: "Aalborg University Vacancies", kind: "丹麦大学官方", cadence: "每周", url: "https://www.vacancies.aau.dk/", note: "可靠电力电子中心是重点团队。" },
    { country: "北欧", name: "Jobbnorge", kind: "挪威学术／公共职缺", cadence: "每日", url: "https://www.jobbnorge.no/search/en", note: "NTNU、SINTEF、UiO 常用入口。" },
    { country: "北欧", name: "NTNU Vacancies", kind: "挪威大学官方", cadence: "每周", url: "https://www.ntnu.edu/vacancies", note: "追踪 power electronics 与 semiconductor research。" },
    { country: "北欧", name: "Study in Finland · Doctoral Admissions", kind: "芬兰官方升学入口", cadence: "每周", url: "https://www.studyinfinland.fi/admissions/doctoral-admissions", note: "先确认 doctoral study right，再另查 paid doctoral researcher position 或 funding。" },
    { country: "北欧", name: "Work in Finland · Academic", kind: "芬兰工作职缺入口", cadence: "每周", url: "https://www.workinfinland.com/en/open-jobs/", note: "用 doctoral researcher、semiconductor、power electronics 寻找受薪职位。" },
  ];

  const SEARCH_MATRIX = [
    { level: "器件", terms: "GaN HEMT / p-GaN gate / III-Nitride / wide-bandgap semiconductor / power semiconductor device" },
    { level: "可靠度", terms: "gate reliability / degradation / dynamic RON / trapping / threshold instability / breakdown" },
    { level: "方法", terms: "TCAD / device simulation / electrical characterization / reliability testing / failure analysis" },
    { level: "系统延伸", terms: "power electronics / gate driver / high-frequency converter / WBG power conversion" },
    { level: "职称变体", terms: "PhD position / doctoral researcher / doctoral candidate / research fellow / Doktorand / Wissenschaftlicher Mitarbeiter" },
    { level: "德国专用", terms: "GaN Leistungselektronik / Halbleiterbauelemente / Zuverlässigkeit + Wissenschaftlicher Mitarbeiter" },
    { level: "法国专用", terms: "sujet de thèse GaN / HEMT / électronique de puissance" },
    { level: "北欧专用", terms: "doctoral student / PhD research fellow + semiconductor / power electronics" },
  ];
  const TRIAGE = [
    { q: "Who employs / pays me?", hint: "University employee／scholarship／external grant／没写？" },
    { q: "Is funding guaranteed?", hint: "公告是否明写 fully funded、salary、contract、stipend？" },
    { q: "What exactly am I applying to?", hint: "PhD vacancy、doctoral programme、doctoral school，还是 PI 自行收生？" },
    { q: "Is supervisor contact required?", hint: "必须先找 PI，还是直接 HR portal 投递？" },
    { q: "What is the coursework load?", hint: "programme-specific；北欧部分学校可达约 30 ECTS。" },
    { q: "What happens after PI says yes?", hint: "是否仍要 university admission／HR contract／doctoral school enrolment？" },
  ];

  root.EU_RADAR = { VERIFIED_AT, GROUPS, SYSTEMS, JOBS, SOURCES, SEARCH_MATRIX, TRIAGE };
})(globalThis);
