window.IELTS_PLANNER_DATA = {
  "generatedAt": "2026-07-21T00:00:00.000+08:00",
  "source": "Planner v38: cleared everything before 7/21; two-pool scheme 7/21-8/10 — pool1 (Cambridge 17-21 full, must-do) descending C21T4->C17T1 as daily base on 7/21-8/9; pool2 (Cambridge 16 and below, listening+writing only) descending from C16T4 placed on 16 listed dates",
  "mainPlan": [
    {
      "id": "main-1",
      "date": "2026-07-21",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "完整模考",
      "ieltsPlan": "完整模考 Cambridge 21 Test 4",
      "ieltsModule": "完整模考 Cambridge 21 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；当日总体安排时间：约4小时",
      "cambridge": "C21T4",
      "trainingItems": [
        {
          "id": "full-C21T4",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 21 Test 4",
          "cambridge": "C21T4",
          "full": "Cambridge 21 Test 4",
          "module": "完整模考 Cambridge 21 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-2",
      "date": "2026-07-22",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "完整模考",
      "ieltsPlan": "完整模考 Cambridge 21 Test 3",
      "ieltsModule": "完整模考 Cambridge 21 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；当日总体安排时间：约4小时",
      "cambridge": "C21T3",
      "trainingItems": [
        {
          "id": "full-C21T3",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 21 Test 3",
          "cambridge": "C21T3",
          "full": "Cambridge 21 Test 3",
          "module": "完整模考 Cambridge 21 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-3",
      "date": "2026-07-23",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 21 Test 2 / 听力+写作 Cambridge 16 Test 4",
      "ieltsModule": "完整模考 Cambridge 21 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 16 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C21T2 + C16T4",
      "trainingItems": [
        {
          "id": "full-C21T2",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 21 Test 2",
          "cambridge": "C21T2",
          "full": "Cambridge 21 Test 2",
          "module": "完整模考 Cambridge 21 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C16T4",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 16 Test 4",
          "cambridge": "C16T4",
          "full": "Cambridge 16 Test 4",
          "module": "听力+写作 Cambridge 16 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-4",
      "date": "2026-07-24",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "完整模考",
      "ieltsPlan": "完整模考 Cambridge 21 Test 1",
      "ieltsModule": "完整模考 Cambridge 21 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；当日总体安排时间：约4小时",
      "cambridge": "C21T1",
      "trainingItems": [
        {
          "id": "full-C21T1",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 21 Test 1",
          "cambridge": "C21T1",
          "full": "Cambridge 21 Test 1",
          "module": "完整模考 Cambridge 21 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-5",
      "date": "2026-07-25",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 20 Test 4 / 听力+写作 Cambridge 16 Test 3",
      "ieltsModule": "完整模考 Cambridge 20 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 16 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C20T4 + C16T3",
      "trainingItems": [
        {
          "id": "full-C20T4",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 20 Test 4",
          "cambridge": "C20T4",
          "full": "Cambridge 20 Test 4",
          "module": "完整模考 Cambridge 20 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C16T3",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 16 Test 3",
          "cambridge": "C16T3",
          "full": "Cambridge 16 Test 3",
          "module": "听力+写作 Cambridge 16 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-6",
      "date": "2026-07-26",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 20 Test 3 / 听力+写作 Cambridge 16 Test 2",
      "ieltsModule": "完整模考 Cambridge 20 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 16 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C20T3 + C16T2",
      "trainingItems": [
        {
          "id": "full-C20T3",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 20 Test 3",
          "cambridge": "C20T3",
          "full": "Cambridge 20 Test 3",
          "module": "完整模考 Cambridge 20 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C16T2",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 16 Test 2",
          "cambridge": "C16T2",
          "full": "Cambridge 16 Test 2",
          "module": "听力+写作 Cambridge 16 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-7",
      "date": "2026-07-27",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 20 Test 2 / 听力+写作 Cambridge 16 Test 1",
      "ieltsModule": "完整模考 Cambridge 20 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 16 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C20T2 + C16T1",
      "trainingItems": [
        {
          "id": "full-C20T2",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 20 Test 2",
          "cambridge": "C20T2",
          "full": "Cambridge 20 Test 2",
          "module": "完整模考 Cambridge 20 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C16T1",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 16 Test 1",
          "cambridge": "C16T1",
          "full": "Cambridge 16 Test 1",
          "module": "听力+写作 Cambridge 16 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-8",
      "date": "2026-07-28",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 20 Test 1 / 听力+写作 Cambridge 15 Test 4",
      "ieltsModule": "完整模考 Cambridge 20 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 15 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C20T1 + C15T4",
      "trainingItems": [
        {
          "id": "full-C20T1",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 20 Test 1",
          "cambridge": "C20T1",
          "full": "Cambridge 20 Test 1",
          "module": "完整模考 Cambridge 20 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C15T4",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 15 Test 4",
          "cambridge": "C15T4",
          "full": "Cambridge 15 Test 4",
          "module": "听力+写作 Cambridge 15 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-9",
      "date": "2026-07-29",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "完整模考",
      "ieltsPlan": "完整模考 Cambridge 19 Test 4",
      "ieltsModule": "完整模考 Cambridge 19 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；当日总体安排时间：约4小时",
      "cambridge": "C19T4",
      "trainingItems": [
        {
          "id": "full-C19T4",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 19 Test 4",
          "cambridge": "C19T4",
          "full": "Cambridge 19 Test 4",
          "module": "完整模考 Cambridge 19 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-10",
      "date": "2026-07-30",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 19 Test 3 / 听力+写作 Cambridge 15 Test 3",
      "ieltsModule": "完整模考 Cambridge 19 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 15 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C19T3 + C15T3",
      "trainingItems": [
        {
          "id": "full-C19T3",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 19 Test 3",
          "cambridge": "C19T3",
          "full": "Cambridge 19 Test 3",
          "module": "完整模考 Cambridge 19 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C15T3",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 15 Test 3",
          "cambridge": "C15T3",
          "full": "Cambridge 15 Test 3",
          "module": "听力+写作 Cambridge 15 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-11",
      "date": "2026-07-31",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "完整模考",
      "ieltsPlan": "完整模考 Cambridge 19 Test 2",
      "ieltsModule": "完整模考 Cambridge 19 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；当日总体安排时间：约4小时",
      "cambridge": "C19T2",
      "trainingItems": [
        {
          "id": "full-C19T2",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 19 Test 2",
          "cambridge": "C19T2",
          "full": "Cambridge 19 Test 2",
          "module": "完整模考 Cambridge 19 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-12",
      "date": "2026-08-01",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 19 Test 1 / 听力+写作 Cambridge 15 Test 2",
      "ieltsModule": "完整模考 Cambridge 19 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 15 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C19T1 + C15T2",
      "trainingItems": [
        {
          "id": "full-C19T1",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 19 Test 1",
          "cambridge": "C19T1",
          "full": "Cambridge 19 Test 1",
          "module": "完整模考 Cambridge 19 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C15T2",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 15 Test 2",
          "cambridge": "C15T2",
          "full": "Cambridge 15 Test 2",
          "module": "听力+写作 Cambridge 15 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-13",
      "date": "2026-08-02",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 18 Test 4 / 听力+写作 Cambridge 15 Test 1",
      "ieltsModule": "完整模考 Cambridge 18 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 15 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C18T4 + C15T1",
      "trainingItems": [
        {
          "id": "full-C18T4",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 18 Test 4",
          "cambridge": "C18T4",
          "full": "Cambridge 18 Test 4",
          "module": "完整模考 Cambridge 18 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C15T1",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 15 Test 1",
          "cambridge": "C15T1",
          "full": "Cambridge 15 Test 1",
          "module": "听力+写作 Cambridge 15 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-14",
      "date": "2026-08-03",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 18 Test 3 / 听力+写作 Cambridge 14 Test 4",
      "ieltsModule": "完整模考 Cambridge 18 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 14 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C18T3 + C14T4",
      "trainingItems": [
        {
          "id": "full-C18T3",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 18 Test 3",
          "cambridge": "C18T3",
          "full": "Cambridge 18 Test 3",
          "module": "完整模考 Cambridge 18 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C14T4",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 14 Test 4",
          "cambridge": "C14T4",
          "full": "Cambridge 14 Test 4",
          "module": "听力+写作 Cambridge 14 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-15",
      "date": "2026-08-04",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 18 Test 2 / 听力+写作 Cambridge 14 Test 3",
      "ieltsModule": "完整模考 Cambridge 18 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 14 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C18T2 + C14T3",
      "trainingItems": [
        {
          "id": "full-C18T2",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 18 Test 2",
          "cambridge": "C18T2",
          "full": "Cambridge 18 Test 2",
          "module": "完整模考 Cambridge 18 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C14T3",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 14 Test 3",
          "cambridge": "C14T3",
          "full": "Cambridge 14 Test 3",
          "module": "听力+写作 Cambridge 14 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-16",
      "date": "2026-08-05",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 18 Test 1 / 听力+写作 Cambridge 14 Test 2",
      "ieltsModule": "完整模考 Cambridge 18 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 14 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C18T1 + C14T2",
      "trainingItems": [
        {
          "id": "full-C18T1",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 18 Test 1",
          "cambridge": "C18T1",
          "full": "Cambridge 18 Test 1",
          "module": "完整模考 Cambridge 18 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C14T2",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 14 Test 2",
          "cambridge": "C14T2",
          "full": "Cambridge 14 Test 2",
          "module": "听力+写作 Cambridge 14 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-17",
      "date": "2026-08-06",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 17 Test 4 / 听力+写作 Cambridge 14 Test 1",
      "ieltsModule": "完整模考 Cambridge 17 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 14 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C17T4 + C14T1",
      "trainingItems": [
        {
          "id": "full-C17T4",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 17 Test 4",
          "cambridge": "C17T4",
          "full": "Cambridge 17 Test 4",
          "module": "完整模考 Cambridge 17 Test 4：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C14T1",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 14 Test 1",
          "cambridge": "C14T1",
          "full": "Cambridge 14 Test 1",
          "module": "听力+写作 Cambridge 14 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-18",
      "date": "2026-08-07",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 17 Test 3 / 听力+写作 Cambridge 13 Test 4",
      "ieltsModule": "完整模考 Cambridge 17 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 13 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C17T3 + C13T4",
      "trainingItems": [
        {
          "id": "full-C17T3",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 17 Test 3",
          "cambridge": "C17T3",
          "full": "Cambridge 17 Test 3",
          "module": "完整模考 Cambridge 17 Test 3：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C13T4",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 13 Test 4",
          "cambridge": "C13T4",
          "full": "Cambridge 13 Test 4",
          "module": "听力+写作 Cambridge 13 Test 4：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-19",
      "date": "2026-08-08",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 17 Test 2 / 听力+写作 Cambridge 13 Test 3",
      "ieltsModule": "完整模考 Cambridge 17 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 13 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C17T2 + C13T3",
      "trainingItems": [
        {
          "id": "full-C17T2",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 17 Test 2",
          "cambridge": "C17T2",
          "full": "Cambridge 17 Test 2",
          "module": "完整模考 Cambridge 17 Test 2：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C13T3",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 13 Test 3",
          "cambridge": "C13T3",
          "full": "Cambridge 13 Test 3",
          "module": "听力+写作 Cambridge 13 Test 3：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-20",
      "date": "2026-08-09",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "完整模考 + 听力+写作",
      "ieltsPlan": "完整模考 Cambridge 17 Test 1 / 听力+写作 Cambridge 13 Test 2",
      "ieltsModule": "完整模考 Cambridge 17 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时；听力+写作 Cambridge 13 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约6-6.5小时",
      "cambridge": "C17T1 + C13T2",
      "trainingItems": [
        {
          "id": "full-C17T1",
          "order": 1,
          "kind": "full",
          "label": "完整模考",
          "title": "完整模考 Cambridge 17 Test 1",
          "cambridge": "C17T1",
          "full": "Cambridge 17 Test 1",
          "module": "完整模考 Cambridge 17 Test 1：听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "duration": "约4小时",
          "detail": "听力40分钟 + 阅读60分钟 + 写作60分钟 + 口语/对话15分钟 + 1小时细整理；单套总用时约4小时",
          "status": "未开始"
        },
        {
          "id": "lw-C13T2",
          "order": 2,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 13 Test 2",
          "cambridge": "C13T2",
          "full": "Cambridge 13 Test 2",
          "module": "听力+写作 Cambridge 13 Test 2：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-21",
      "date": "2026-08-10",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "听力+写作",
      "ieltsPlan": "听力+写作 Cambridge 13 Test 1",
      "ieltsModule": "听力+写作 Cambridge 13 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时；当日总体安排时间：约2-2.5小时",
      "cambridge": "C13T1",
      "trainingItems": [
        {
          "id": "lw-C13T1",
          "order": 1,
          "kind": "lw",
          "label": "听力+写作",
          "title": "听力+写作 Cambridge 13 Test 1",
          "cambridge": "C13T1",
          "full": "Cambridge 13 Test 1",
          "module": "听力+写作 Cambridge 13 Test 1：听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "duration": "约2-2.5小时",
          "detail": "听力必做40分钟 + 写作必做60分钟 + 整理30分钟；单项约2-2.5小时",
          "status": "未开始"
        }
      ],
      "projectType": "",
      "projectPlan": "",
      "limits": "第一池 Cambridge 17-21 完整必做（每日打底）；第二池 Cambridge 16 及以下只做听力+写作",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    }
  ],
  "dailyTemplates": [
    {
      "id": "daily-1",
      "date": "2026-07-21",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 21 Test 4；单套约4小时",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 21 Test 4",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-2",
      "date": "2026-07-22",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 21 Test 3；单套约4小时",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 21 Test 3",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-3",
      "date": "2026-07-23",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 21 Test 2；单套约4小时",
      "afternoon": "听力+写作 Cambridge 16 Test 4；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 21 Test 2 / 听力+写作 Cambridge 16 Test 4",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-4",
      "date": "2026-07-24",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 21 Test 1；单套约4小时",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 21 Test 1",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-5",
      "date": "2026-07-25",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 20 Test 4；单套约4小时",
      "afternoon": "听力+写作 Cambridge 16 Test 3；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 20 Test 4 / 听力+写作 Cambridge 16 Test 3",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-6",
      "date": "2026-07-26",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 20 Test 3；单套约4小时",
      "afternoon": "听力+写作 Cambridge 16 Test 2；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 20 Test 3 / 听力+写作 Cambridge 16 Test 2",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-7",
      "date": "2026-07-27",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 20 Test 2；单套约4小时",
      "afternoon": "听力+写作 Cambridge 16 Test 1；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 20 Test 2 / 听力+写作 Cambridge 16 Test 1",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-8",
      "date": "2026-07-28",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 20 Test 1；单套约4小时",
      "afternoon": "听力+写作 Cambridge 15 Test 4；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 20 Test 1 / 听力+写作 Cambridge 15 Test 4",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-9",
      "date": "2026-07-29",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 19 Test 4；单套约4小时",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 19 Test 4",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-10",
      "date": "2026-07-30",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 19 Test 3；单套约4小时",
      "afternoon": "听力+写作 Cambridge 15 Test 3；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 19 Test 3 / 听力+写作 Cambridge 15 Test 3",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-11",
      "date": "2026-07-31",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 19 Test 2；单套约4小时",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 19 Test 2",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-12",
      "date": "2026-08-01",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 19 Test 1；单套约4小时",
      "afternoon": "听力+写作 Cambridge 15 Test 2；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 19 Test 1 / 听力+写作 Cambridge 15 Test 2",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-13",
      "date": "2026-08-02",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 18 Test 4；单套约4小时",
      "afternoon": "听力+写作 Cambridge 15 Test 1；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 18 Test 4 / 听力+写作 Cambridge 15 Test 1",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-14",
      "date": "2026-08-03",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 18 Test 3；单套约4小时",
      "afternoon": "听力+写作 Cambridge 14 Test 4；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 18 Test 3 / 听力+写作 Cambridge 14 Test 4",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-15",
      "date": "2026-08-04",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 18 Test 2；单套约4小时",
      "afternoon": "听力+写作 Cambridge 14 Test 3；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 18 Test 2 / 听力+写作 Cambridge 14 Test 3",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-16",
      "date": "2026-08-05",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 18 Test 1；单套约4小时",
      "afternoon": "听力+写作 Cambridge 14 Test 2；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 18 Test 1 / 听力+写作 Cambridge 14 Test 2",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-17",
      "date": "2026-08-06",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 17 Test 4；单套约4小时",
      "afternoon": "听力+写作 Cambridge 14 Test 1；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 17 Test 4 / 听力+写作 Cambridge 14 Test 1",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-18",
      "date": "2026-08-07",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 17 Test 3；单套约4小时",
      "afternoon": "听力+写作 Cambridge 13 Test 4；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 17 Test 3 / 听力+写作 Cambridge 13 Test 4",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-19",
      "date": "2026-08-08",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 17 Test 2；单套约4小时",
      "afternoon": "听力+写作 Cambridge 13 Test 3；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 17 Test 2 / 听力+写作 Cambridge 13 Test 3",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-20",
      "date": "2026-08-09",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "完整模考 Cambridge 17 Test 1；单套约4小时",
      "afternoon": "听力+写作 Cambridge 13 Test 2；约2-2.5小时",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "完整模考 Cambridge 17 Test 1 / 听力+写作 Cambridge 13 Test 2",
      "notes": "第一池完整必做；第二池只做听力+写作"
    },
    {
      "id": "daily-21",
      "date": "2026-08-10",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "听力+写作 Cambridge 13 Test 1；约2-2.5小时",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "听力+写作 Cambridge 13 Test 1",
      "notes": "第一池完整必做；第二池只做听力+写作"
    }
  ],
  "planVersion": "2026-07-21-two-pool-p1full-p2lw-v38",
  "resetFromDate": "2026-07-20"
};
