window.IELTS_PLANNER_DATA = {
  "generatedAt": "2026-06-25T00:00:00.000+08:00",
  "source": "Planner reset v12: visible plan starts on 2026-06-25 with the Cambridge sequence offset applied",
  "mainPlan": [
    {
      "id": "main-1",
      "date": "2026-06-25",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 7 Test 1 / 晚 Cambridge 7 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 7 Test 1；晚上 19:00-22:00：Cambridge 7 Test 2；其他时段可选",
      "cambridge": "C7T1 + C7T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-2",
      "date": "2026-06-26",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 7 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 7 Test 3；其他时段可选",
      "cambridge": "C7T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-3",
      "date": "2026-06-27",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 7 Test 4 / 晚 Cambridge 8 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 7 Test 4；晚上 19:00-22:00：Cambridge 8 Test 1；其他时段可选",
      "cambridge": "C7T4 + C8T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-4",
      "date": "2026-06-28",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 8 Test 2 / 晚 Cambridge 8 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 8 Test 2；晚上 19:00-22:00：Cambridge 8 Test 3；其他时段可选",
      "cambridge": "C8T2 + C8T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-5",
      "date": "2026-06-29",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 8 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 8 Test 4；其他时段可选",
      "cambridge": "C8T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-6",
      "date": "2026-06-30",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 9 Test 1 / 晚 Cambridge 9 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 9 Test 1；晚上 19:00-22:00：Cambridge 9 Test 2；其他时段可选",
      "cambridge": "C9T1 + C9T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-7",
      "date": "2026-07-01",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 9 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 9 Test 3；其他时段可选",
      "cambridge": "C9T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-8",
      "date": "2026-07-02",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 9 Test 4 / 晚 Cambridge 10 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 9 Test 4；晚上 19:00-22:00：Cambridge 10 Test 1；其他时段可选",
      "cambridge": "C9T4 + C10T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-9",
      "date": "2026-07-03",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 10 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 10 Test 2；其他时段可选",
      "cambridge": "C10T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-10",
      "date": "2026-07-04",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 10 Test 3 / 晚 Cambridge 10 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 10 Test 3；晚上 19:00-22:00：Cambridge 10 Test 4；其他时段可选",
      "cambridge": "C10T3 + C10T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-11",
      "date": "2026-07-05",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 11 Test 1 / 晚 Cambridge 11 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 11 Test 1；晚上 19:00-22:00：Cambridge 11 Test 2；其他时段可选",
      "cambridge": "C11T1 + C11T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-12",
      "date": "2026-07-06",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 11 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 11 Test 3；其他时段可选",
      "cambridge": "C11T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-13",
      "date": "2026-07-07",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 11 Test 4 / 晚 Cambridge 12 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 11 Test 4；晚上 19:00-22:00：Cambridge 12 Test 1；其他时段可选",
      "cambridge": "C11T4 + C12T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-14",
      "date": "2026-07-08",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 12 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 12 Test 2；其他时段可选",
      "cambridge": "C12T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-15",
      "date": "2026-07-09",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 12 Test 3 / 晚 Cambridge 12 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 12 Test 3；晚上 19:00-22:00：Cambridge 12 Test 4；其他时段可选",
      "cambridge": "C12T3 + C12T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-16",
      "date": "2026-07-10",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 13 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 13 Test 1；其他时段可选",
      "cambridge": "C13T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-17",
      "date": "2026-07-11",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 13 Test 2 / 晚 Cambridge 13 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 13 Test 2；晚上 19:00-22:00：Cambridge 13 Test 3；其他时段可选",
      "cambridge": "C13T2 + C13T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-18",
      "date": "2026-07-12",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 13 Test 4 / 晚 Cambridge 14 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 13 Test 4；晚上 19:00-22:00：Cambridge 14 Test 1；其他时段可选",
      "cambridge": "C13T4 + C14T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-19",
      "date": "2026-07-13",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 14 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 14 Test 2；其他时段可选",
      "cambridge": "C14T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-20",
      "date": "2026-07-14",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 14 Test 3 / 晚 Cambridge 14 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 14 Test 3；晚上 19:00-22:00：Cambridge 14 Test 4；其他时段可选",
      "cambridge": "C14T3 + C14T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-21",
      "date": "2026-07-15",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 15 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 15 Test 1；其他时段可选",
      "cambridge": "C15T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-22",
      "date": "2026-07-16",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 15 Test 2 / 晚 Cambridge 15 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 15 Test 2；晚上 19:00-22:00：Cambridge 15 Test 3；其他时段可选",
      "cambridge": "C15T2 + C15T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-23",
      "date": "2026-07-17",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 15 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 15 Test 4；其他时段可选",
      "cambridge": "C15T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-24",
      "date": "2026-07-18",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 16 Test 1 / 晚 Cambridge 16 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 16 Test 1；晚上 19:00-22:00：Cambridge 16 Test 2；其他时段可选",
      "cambridge": "C16T1 + C16T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-25",
      "date": "2026-07-19",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 16 Test 3 / 晚 Cambridge 16 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 16 Test 3；晚上 19:00-22:00：Cambridge 16 Test 4；其他时段可选",
      "cambridge": "C16T3 + C16T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-26",
      "date": "2026-07-20",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 17 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 17 Test 1；其他时段可选",
      "cambridge": "C17T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-27",
      "date": "2026-07-21",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 17 Test 2 / 晚 Cambridge 17 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 17 Test 2；晚上 19:00-22:00：Cambridge 17 Test 3；其他时段可选",
      "cambridge": "C17T2 + C17T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-28",
      "date": "2026-07-22",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 17 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 17 Test 4；其他时段可选",
      "cambridge": "C17T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-29",
      "date": "2026-07-23",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 18 Test 1 / 晚 Cambridge 18 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 18 Test 1；晚上 19:00-22:00：Cambridge 18 Test 2；其他时段可选",
      "cambridge": "C18T1 + C18T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-30",
      "date": "2026-07-24",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 18 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 18 Test 3；其他时段可选",
      "cambridge": "C18T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-31",
      "date": "2026-07-25",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 18 Test 4 / 晚 Cambridge 19 Test 1",
      "ieltsModule": "早上 8:30-11:30：Cambridge 18 Test 4；晚上 19:00-22:00：Cambridge 19 Test 1；其他时段可选",
      "cambridge": "C18T4 + C19T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-32",
      "date": "2026-07-26",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 19 Test 2 / 晚 Cambridge 19 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 19 Test 2；晚上 19:00-22:00：Cambridge 19 Test 3；其他时段可选",
      "cambridge": "C19T2 + C19T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-33",
      "date": "2026-07-27",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 19 Test 4",
      "ieltsModule": "早上 8:30-11:30：Cambridge 19 Test 4；其他时段可选",
      "cambridge": "C19T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-34",
      "date": "2026-07-28",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 20 Test 1 / 晚 Cambridge 20 Test 2",
      "ieltsModule": "早上 8:30-11:30：Cambridge 20 Test 1；晚上 19:00-22:00：Cambridge 20 Test 2；其他时段可选",
      "cambridge": "C20T1 + C20T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-35",
      "date": "2026-07-29",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 20 Test 3",
      "ieltsModule": "早上 8:30-11:30：Cambridge 20 Test 3；其他时段可选",
      "cambridge": "C20T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-36",
      "date": "2026-07-30",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge 20 Test 4 / 晚 Cambridge extra 61",
      "ieltsModule": "早上 8:30-11:30：Cambridge 20 Test 4；晚上 19:00-22:00：Cambridge extra 61；其他时段可选",
      "cambridge": "C20T4 + Cextra 61",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-37",
      "date": "2026-07-31",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge extra 62",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 62；其他时段可选",
      "cambridge": "Cextra 62",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-38",
      "date": "2026-08-01",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge extra 63 / 晚 Cambridge extra 64",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 63；晚上 19:00-22:00：Cambridge extra 64；其他时段可选",
      "cambridge": "Cextra 63 + Cextra 64",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-39",
      "date": "2026-08-02",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge extra 65 / 晚 Cambridge extra 66",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 65；晚上 19:00-22:00：Cambridge extra 66；其他时段可选",
      "cambridge": "Cextra 65 + Cextra 66",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-40",
      "date": "2026-08-03",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge extra 67",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 67；其他时段可选",
      "cambridge": "Cextra 67",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-41",
      "date": "2026-08-04",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge extra 68 / 晚 Cambridge extra 69",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 68；晚上 19:00-22:00：Cambridge extra 69；其他时段可选",
      "cambridge": "Cextra 68 + Cextra 69",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-42",
      "date": "2026-08-05",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge extra 70",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 70；其他时段可选",
      "cambridge": "Cextra 70",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期一/三/五只安排一份完整雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-43",
      "date": "2026-08-06",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "双份雅思",
      "ieltsPlan": "早 Cambridge extra 71 / 晚 Cambridge extra 72",
      "ieltsModule": "早上 8:30-11:30：Cambridge extra 71；晚上 19:00-22:00：Cambridge extra 72；其他时段可选",
      "cambridge": "Cextra 71 + Cextra 72",
      "projectType": "",
      "projectPlan": "",
      "limits": "星期二/四/六/日安排早晚两份雅思；其他时段可选",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    }
  ],
  "dailyTemplates": [
    {
      "id": "daily-1",
      "date": "2026-06-25",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 7 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 7 Test 2｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 7 Test 1 / 晚 Cambridge 7 Test 2",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-2",
      "date": "2026-06-26",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 7 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 7 Test 3",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-3",
      "date": "2026-06-27",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 7 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 8 Test 1｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 7 Test 4 / 晚 Cambridge 8 Test 1",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-4",
      "date": "2026-06-28",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 8 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 8 Test 3｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 8 Test 2 / 晚 Cambridge 8 Test 3",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-5",
      "date": "2026-06-29",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 8 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 8 Test 4",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-6",
      "date": "2026-06-30",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 9 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 9 Test 2｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 9 Test 1 / 晚 Cambridge 9 Test 2",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-7",
      "date": "2026-07-01",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 9 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 9 Test 3",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-8",
      "date": "2026-07-02",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 9 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 10 Test 1｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 9 Test 4 / 晚 Cambridge 10 Test 1",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-9",
      "date": "2026-07-03",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 10 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 10 Test 2",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-10",
      "date": "2026-07-04",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 10 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 10 Test 4｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 10 Test 3 / 晚 Cambridge 10 Test 4",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-11",
      "date": "2026-07-05",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 11 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 11 Test 2｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 11 Test 1 / 晚 Cambridge 11 Test 2",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-12",
      "date": "2026-07-06",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 11 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 11 Test 3",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-13",
      "date": "2026-07-07",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 11 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 12 Test 1｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 11 Test 4 / 晚 Cambridge 12 Test 1",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-14",
      "date": "2026-07-08",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 12 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 12 Test 2",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-15",
      "date": "2026-07-09",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 12 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 12 Test 4｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 12 Test 3 / 晚 Cambridge 12 Test 4",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-16",
      "date": "2026-07-10",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 13 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 13 Test 1",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-17",
      "date": "2026-07-11",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 13 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 13 Test 3｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 13 Test 2 / 晚 Cambridge 13 Test 3",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-18",
      "date": "2026-07-12",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 13 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 14 Test 1｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 13 Test 4 / 晚 Cambridge 14 Test 1",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-19",
      "date": "2026-07-13",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 14 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 14 Test 2",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-20",
      "date": "2026-07-14",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 14 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 14 Test 4｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 14 Test 3 / 晚 Cambridge 14 Test 4",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-21",
      "date": "2026-07-15",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 15 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 15 Test 1",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-22",
      "date": "2026-07-16",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 15 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 15 Test 3｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 15 Test 2 / 晚 Cambridge 15 Test 3",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-23",
      "date": "2026-07-17",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 15 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 15 Test 4",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-24",
      "date": "2026-07-18",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 16 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 16 Test 2｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 16 Test 1 / 晚 Cambridge 16 Test 2",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-25",
      "date": "2026-07-19",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 16 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 16 Test 4｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 16 Test 3 / 晚 Cambridge 16 Test 4",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-26",
      "date": "2026-07-20",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 17 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 17 Test 1",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-27",
      "date": "2026-07-21",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 17 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 17 Test 3｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 17 Test 2 / 晚 Cambridge 17 Test 3",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-28",
      "date": "2026-07-22",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 17 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 17 Test 4",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-29",
      "date": "2026-07-23",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 18 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 18 Test 2｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 18 Test 1 / 晚 Cambridge 18 Test 2",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-30",
      "date": "2026-07-24",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 18 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 18 Test 3",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-31",
      "date": "2026-07-25",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 18 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 19 Test 1｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 18 Test 4 / 晚 Cambridge 19 Test 1",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-32",
      "date": "2026-07-26",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 19 Test 2｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 19 Test 3｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 19 Test 2 / 晚 Cambridge 19 Test 3",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-33",
      "date": "2026-07-27",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 19 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 19 Test 4",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-34",
      "date": "2026-07-28",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 20 Test 1｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 20 Test 2｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 20 Test 1 / 晚 Cambridge 20 Test 2",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-35",
      "date": "2026-07-29",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge 20 Test 3｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 20 Test 3",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-36",
      "date": "2026-07-30",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge 20 Test 4｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge extra 61｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge 20 Test 4 / 晚 Cambridge extra 61",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-37",
      "date": "2026-07-31",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge extra 62｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge extra 62",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-38",
      "date": "2026-08-01",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge extra 63｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge extra 64｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge extra 63 / 晚 Cambridge extra 64",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-39",
      "date": "2026-08-02",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge extra 65｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge extra 66｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge extra 65 / 晚 Cambridge extra 66",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-40",
      "date": "2026-08-03",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge extra 67｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge extra 67",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-41",
      "date": "2026-08-04",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge extra 68｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge extra 69｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge extra 68 / 晚 Cambridge extra 69",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-42",
      "date": "2026-08-05",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天若体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 听力热身",
      "morningCore": "Cambridge extra 70｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排 / 午休 / 整理错题，不强制",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge extra 70",
      "notes": "星期一/三/五安排一份雅思；其他时段都是可选安排。"
    },
    {
      "id": "daily-43",
      "date": "2026-08-06",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 今日启动",
      "morningCore": "Cambridge extra 71｜雅思 8:30-11:30",
      "afternoon": "可选：自由安排；实验专案先留空",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge extra 72｜雅思 19:00-22:00",
      "mainTask": "早 Cambridge extra 71 / 晚 Cambridge extra 72",
      "notes": "星期二/四/六/日安排早晚两份雅思；其他时段都是可选安排。"
    }
  ],
  "planVersion": "2026-06-25-cambridge-6-reset-v12",
  "resetFromDate": "2026-06-25"
};
