window.IELTS_PLANNER_DATA = {
  "generatedAt": "2026-07-11T00:00:00.000+08:00",
  "source": "Planner reset v19: visible plan starts on 2026-07-11, Cambridge sequence restarts at C7T1 and stops after C20T4, 07-14/15/16/18/20/21/22 run one test, and every other day runs three tests with no preset time slots",
  "mainPlan": [
    {
      "id": "main-1",
      "date": "2026-07-11",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 7 Test 1 / 中 Cambridge 7 Test 2 / 晚 Cambridge 7 Test 3",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C7T1 + C7T2 + C7T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-2",
      "date": "2026-07-12",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 7 Test 4 / 中 Cambridge 8 Test 1 / 晚 Cambridge 8 Test 2",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C7T4 + C8T1 + C8T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-3",
      "date": "2026-07-13",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 8 Test 3 / 中 Cambridge 8 Test 4 / 晚 Cambridge 9 Test 1",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C8T3 + C8T4 + C9T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-4",
      "date": "2026-07-14",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 9 Test 2",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C9T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-5",
      "date": "2026-07-15",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 9 Test 3",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C9T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-6",
      "date": "2026-07-16",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 9 Test 4",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C9T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-7",
      "date": "2026-07-17",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 10 Test 1 / 中 Cambridge 10 Test 2 / 晚 Cambridge 10 Test 3",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C10T1 + C10T2 + C10T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-8",
      "date": "2026-07-18",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 10 Test 4",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C10T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-9",
      "date": "2026-07-19",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 11 Test 1 / 中 Cambridge 11 Test 2 / 晚 Cambridge 11 Test 3",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C11T1 + C11T2 + C11T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-10",
      "date": "2026-07-20",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 11 Test 4",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C11T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-11",
      "date": "2026-07-21",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 12 Test 1",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C12T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-12",
      "date": "2026-07-22",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 12 Test 2",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C12T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-13",
      "date": "2026-07-23",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 12 Test 3 / 中 Cambridge 12 Test 4 / 晚 Cambridge 13 Test 1",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C12T3 + C12T4 + C13T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-14",
      "date": "2026-07-24",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 13 Test 2 / 中 Cambridge 13 Test 3 / 晚 Cambridge 13 Test 4",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C13T2 + C13T3 + C13T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-15",
      "date": "2026-07-25",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 14 Test 1 / 中 Cambridge 14 Test 2 / 晚 Cambridge 14 Test 3",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C14T1 + C14T2 + C14T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-16",
      "date": "2026-07-26",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 14 Test 4 / 中 Cambridge 15 Test 1 / 晚 Cambridge 15 Test 2",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C14T4 + C15T1 + C15T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-17",
      "date": "2026-07-27",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 15 Test 3 / 中 Cambridge 15 Test 4 / 晚 Cambridge 16 Test 1",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C15T3 + C15T4 + C16T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-18",
      "date": "2026-07-28",
      "weekday": "周二",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 16 Test 2 / 中 Cambridge 16 Test 3 / 晚 Cambridge 16 Test 4",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C16T2 + C16T3 + C16T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-19",
      "date": "2026-07-29",
      "weekday": "周三",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 17 Test 1 / 中 Cambridge 17 Test 2 / 晚 Cambridge 17 Test 3",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C17T1 + C17T2 + C17T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-20",
      "date": "2026-07-30",
      "weekday": "周四",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 17 Test 4 / 中 Cambridge 18 Test 1 / 晚 Cambridge 18 Test 2",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C17T4 + C18T1 + C18T2",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-21",
      "date": "2026-07-31",
      "weekday": "周五",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 18 Test 3 / 中 Cambridge 18 Test 4 / 晚 Cambridge 19 Test 1",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C18T3 + C18T4 + C19T1",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-22",
      "date": "2026-08-01",
      "weekday": "周六",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 19 Test 2 / 中 Cambridge 19 Test 3 / 晚 Cambridge 19 Test 4",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C19T2 + C19T3 + C19T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-23",
      "date": "2026-08-02",
      "weekday": "周日",
      "dayType": "正常",
      "ieltsPriority": "三份雅思",
      "ieltsPlan": "早 Cambridge 20 Test 1 / 中 Cambridge 20 Test 2 / 晚 Cambridge 20 Test 3",
      "ieltsModule": "早中晚各一份（共三份，不设具体时间）",
      "cambridge": "C20T1 + C20T2 + C20T3",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日早中晚共三份雅思，不预设具体时间。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    },
    {
      "id": "main-24",
      "date": "2026-08-03",
      "weekday": "周一",
      "dayType": "正常",
      "ieltsPriority": "单份雅思",
      "ieltsPlan": "Cambridge 20 Test 4",
      "ieltsModule": "做一份雅思（时段自定）",
      "cambridge": "C20T4",
      "projectType": "",
      "projectPlan": "",
      "limits": "今日一份雅思，时段自定。",
      "status": "未开始",
      "actual": "",
      "projectModule": ""
    }
  ],
  "dailyTemplates": [
    {
      "id": "daily-1",
      "date": "2026-07-11",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 7 Test 1",
      "afternoon": "Cambridge 7 Test 2",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 7 Test 3",
      "mainTask": "早 Cambridge 7 Test 1 / 中 Cambridge 7 Test 2 / 晚 Cambridge 7 Test 3",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-2",
      "date": "2026-07-12",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 7 Test 4",
      "afternoon": "Cambridge 8 Test 1",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 8 Test 2",
      "mainTask": "早 Cambridge 7 Test 4 / 中 Cambridge 8 Test 1 / 晚 Cambridge 8 Test 2",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-3",
      "date": "2026-07-13",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 8 Test 3",
      "afternoon": "Cambridge 8 Test 4",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 9 Test 1",
      "mainTask": "早 Cambridge 8 Test 3 / 中 Cambridge 8 Test 4 / 晚 Cambridge 9 Test 1",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-4",
      "date": "2026-07-14",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 9 Test 2（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 9 Test 2",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-5",
      "date": "2026-07-15",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 9 Test 3（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 9 Test 3",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-6",
      "date": "2026-07-16",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 9 Test 4（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 9 Test 4",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-7",
      "date": "2026-07-17",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 10 Test 1",
      "afternoon": "Cambridge 10 Test 2",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 10 Test 3",
      "mainTask": "早 Cambridge 10 Test 1 / 中 Cambridge 10 Test 2 / 晚 Cambridge 10 Test 3",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-8",
      "date": "2026-07-18",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 10 Test 4（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 10 Test 4",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-9",
      "date": "2026-07-19",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 11 Test 1",
      "afternoon": "Cambridge 11 Test 2",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 11 Test 3",
      "mainTask": "早 Cambridge 11 Test 1 / 中 Cambridge 11 Test 2 / 晚 Cambridge 11 Test 3",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-10",
      "date": "2026-07-20",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 11 Test 4（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 11 Test 4",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-11",
      "date": "2026-07-21",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 12 Test 1（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 12 Test 1",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-12",
      "date": "2026-07-22",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 12 Test 2（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 12 Test 2",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    },
    {
      "id": "daily-13",
      "date": "2026-07-23",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 12 Test 3",
      "afternoon": "Cambridge 12 Test 4",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 13 Test 1",
      "mainTask": "早 Cambridge 12 Test 3 / 中 Cambridge 12 Test 4 / 晚 Cambridge 13 Test 1",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-14",
      "date": "2026-07-24",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 13 Test 2",
      "afternoon": "Cambridge 13 Test 3",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 13 Test 4",
      "mainTask": "早 Cambridge 13 Test 2 / 中 Cambridge 13 Test 3 / 晚 Cambridge 13 Test 4",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-15",
      "date": "2026-07-25",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 14 Test 1",
      "afternoon": "Cambridge 14 Test 2",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 14 Test 3",
      "mainTask": "早 Cambridge 14 Test 1 / 中 Cambridge 14 Test 2 / 晚 Cambridge 14 Test 3",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-16",
      "date": "2026-07-26",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 14 Test 4",
      "afternoon": "Cambridge 15 Test 1",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 15 Test 2",
      "mainTask": "早 Cambridge 14 Test 4 / 中 Cambridge 15 Test 1 / 晚 Cambridge 15 Test 2",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-17",
      "date": "2026-07-27",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 15 Test 3",
      "afternoon": "Cambridge 15 Test 4",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 16 Test 1",
      "mainTask": "早 Cambridge 15 Test 3 / 中 Cambridge 15 Test 4 / 晚 Cambridge 16 Test 1",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-18",
      "date": "2026-07-28",
      "weekday": "周二",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 16 Test 2",
      "afternoon": "Cambridge 16 Test 3",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 16 Test 4",
      "mainTask": "早 Cambridge 16 Test 2 / 中 Cambridge 16 Test 3 / 晚 Cambridge 16 Test 4",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-19",
      "date": "2026-07-29",
      "weekday": "周三",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 17 Test 1",
      "afternoon": "Cambridge 17 Test 2",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 17 Test 3",
      "mainTask": "早 Cambridge 17 Test 1 / 中 Cambridge 17 Test 2 / 晚 Cambridge 17 Test 3",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-20",
      "date": "2026-07-30",
      "weekday": "周四",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 17 Test 4",
      "afternoon": "Cambridge 18 Test 1",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 18 Test 2",
      "mainTask": "早 Cambridge 17 Test 4 / 中 Cambridge 18 Test 1 / 晚 Cambridge 18 Test 2",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-21",
      "date": "2026-07-31",
      "weekday": "周五",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 18 Test 3",
      "afternoon": "Cambridge 18 Test 4",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 19 Test 1",
      "mainTask": "早 Cambridge 18 Test 3 / 中 Cambridge 18 Test 4 / 晚 Cambridge 19 Test 1",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-22",
      "date": "2026-08-01",
      "weekday": "周六",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 19 Test 2",
      "afternoon": "Cambridge 19 Test 3",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 19 Test 4",
      "mainTask": "早 Cambridge 19 Test 2 / 中 Cambridge 19 Test 3 / 晚 Cambridge 19 Test 4",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-23",
      "date": "2026-08-02",
      "weekday": "周日",
      "dayType": "正常",
      "swim": "晚泳 20:30–21:30；必要时早泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 20 Test 1",
      "afternoon": "Cambridge 20 Test 2",
      "evening": "可选：晚餐 + 缓冲",
      "night": "Cambridge 20 Test 3",
      "mainTask": "早 Cambridge 20 Test 1 / 中 Cambridge 20 Test 2 / 晚 Cambridge 20 Test 3",
      "notes": "今日早中晚共三份雅思；其他时段可选，不预设具体钟点。"
    },
    {
      "id": "daily-24",
      "date": "2026-08-03",
      "weekday": "周一",
      "dayType": "正常",
      "swim": "可选：当天体力允许再安排游泳",
      "morningEarly": "可选：早泳 / 早餐 / 热身",
      "morningCore": "Cambridge 20 Test 4（今日一份，时段自定）",
      "afternoon": "可选：自由安排 / 午休 / 错题整理",
      "evening": "可选：晚餐 + 缓冲",
      "night": "可选：错题 / 单词 / 口语素材轻量收尾",
      "mainTask": "Cambridge 20 Test 4",
      "notes": "今日一份雅思，时段自定；其他时段可选。"
    }
  ],
  "planVersion": "2026-07-11-cambridge-7to20-reset-v19",
  "resetFromDate": "2026-07-11"
};
